/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MemFileSystem */

#ifndef _Included_MemFileSystem
#define _Included_MemFileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MemFileSystem
 * Method:    nrfsConnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsConnect
  (JNIEnv *, jobject);

/*
 * Class:     MemFileSystem
 * Method:    nrfsDisconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsDisconnect
  (JNIEnv *, jobject);

/*
 * Class:     MemFileSystem
 * Method:    nrfsOpenFile
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_MemFileSystem_nrfsOpenFile
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     MemFileSystem
 * Method:    nrfsCloseFile
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsCloseFile
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     MemFileSystem
 * Method:    nrfsMknod
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsMknod
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     MemFileSystem
 * Method:    nrfsAccess
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsAccess
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     MemFileSystem
 * Method:    nrfsGetAttibute
 * Signature: ([B[I)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsGetAttibute
  (JNIEnv *, jobject, jbyteArray, jintArray);

/*
 * Class:     MemFileSystem
 * Method:    nrfsWrite
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsWrite
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     MemFileSystem
 * Method:    nrfsRead
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsRead
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     MemFileSystem
 * Method:    nrfsCreateDirectory
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsCreateDirectory
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     MemFileSystem
 * Method:    nrfsDelete
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsDelete
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     MemFileSystem
 * Method:    nrfsRename
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_MemFileSystem_nrfsRename
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     MemFileSystem
 * Method:    nrfsListDirectory
 * Signature: ([B)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_MemFileSystem_nrfsListDirectory
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
